Add environment variable support for client configuration
GlobalNOC/tsds-telegraf pull request #1
Opened 2021-06-11 20:54 UTC by cammdavie

One piece of functionality we wanted was flexibility when it came to specifying the environment variables, so currently the plugin is set up to get client info (user, password, push url) from the config.yaml file, then override any of those fields if corresponding environment variables have been set.

We also thought it made sense to keep hard-coded environment variable names out of the python plugin and instead define them in the config.yaml file.

We've tested this both in plugin form and container form and haven't found any issues with this change.

2021-08-17 19:18 UTC, runakor commented
Thank you for contribution. I reviewed the codes and it works well. But I concern about the security of storing password on environment variable. Otherwise it looks good to me.

2021-08-17 19:29 UTC, runakor requested changes
Storing password in environment variables can be a security issue. please remove password part.

2021-08-18 18:12 UTC, merged

2021-08-18 18:22 UTC, cammdavie commented
Hi, sorry, I just saw that you merged in the PR. I made some changes to have a password filepath passed in as an environment variable instead of the plaintext password, but ran into some trouble while testing so I haven't finished. Sorry about that! Let me know if you would like this password file path change to be another PR or if there is another plan for secure password storage. Thanks

2021-08-19 15:40 UTC, runakor commented
Hi,  giving password filepath is a good approach to enhance security and I like to see it work. However, I merged the pull request after talking with Dan. we agreed on storing password environment variables is somewhat acceptable in this case. 
I'll review the proposed change when you make a pull request for it. 

Thank you,